package mcts.heavyplayout;

public enum PlacementHeuristicType {
  NONE,
  MAX_FISH_FOR_PENGUIN,
  MAX_TILES_FOR_PENGUIN,
  MAX_FISH_PER_TILE_FOR_PENGUIN,
  MAX_FISH_FOR_ALL_PENGUINS,
  MAX_TILES_FOR_ALL_PENGUINS,
  MAX_FISH_PER_TILE_FOR_ALL_PENGUINS,
  MIN_FISH_FOR_OPPONENT_PENGUINS,
  MIN_TILES_FOR_OPPONENT_PENGUINS,
  MIN_FISH_PER_TILE_FOR_OPPONENT_PENGUINS
}
