package challenge;

public enum MovementHeuristicType {
  NONE,
  MAX_FISH_ON_NEW_TILE,
  MAX_NEW_FISH_FOR_PENGUIN,
  MAX_NEW_TILES_FOR_PENGUIN,
  MAX_NEW_FISH_PER_TILE_FOR_PENGUIN,
  MAX_NEW_FISH_FOR_ALL_PENGUINS,
  MAX_NEW_TILES_FOR_ALL_PENGUINS,
  MAX_NEW_FISH_PER_TILE_FOR_ALL_PENGUINS,
  MIN_NEW_FISH_FOR_OPPONENT_PENGUINS,
  MIN_NEW_TILES_FOR_OPPONENT_PENGUINS,
  MIM_NEW_FISH_PER_TILE_FOR_OPPONENT_PENGUINS
}
